
dist: bionic
sudo: required

script:
 - (guile -L . test.scm)

matrix:
  include:
   - os: linux
     addons:
       apt:
         packages:
           - guile-2.2

before_install:
  - sudo apt-get install guile-2-2
