
name: Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          sudo apt update
          sudo apt install guile-3.0
      - uses: actions/checkout@v3
      - name: test
        run: |
          guile -L mod test.scm
